window.SAYGO_LESSONS = [
  {
    module:'МОДУЛЬ 1 · БУКВЫ И ЗВУКИ', title:'Алфавит: A–H', tag:'ОСНОВА',
    english:'A, B, C, D, E, F, G, H.', meaning:'Это названия первых восьми букв английского алфавита.',
    pronounce:'эй · би · си · ди · и · эф · джи · эйч',
    why:'Нужно, когда называют имя, электронную почту, пароль или код.',
    rule:'Буква и звук — не одно и то же. Сейчас ты запоминаешь только названия букв.',
    tip:'E называется «и», а не русское «е». Слушай образец и повторяй.',
    build:['A','B','C','D','E','F','G','H'], practiceTitle:'Поставь буквы по порядку', practiceHint:'Нажимай буквы от A до H.',
    quiz:{q:'Как по-английски называется буква E?',options:['и','э','эй'],answer:0,explain:'Буква E называется «и».'},
    outcome:'Ты знаешь буквы A–H и можешь услышать их в имени или коде.'
  },
  {
    module:'МОДУЛЬ 1 · БУКВЫ И ЗВУКИ', title:'Алфавит: I–P', tag:'ОСНОВА',
    english:'I, J, K, L, M, N, O, P.', meaning:'Следующие восемь названий английских букв.',
    pronounce:'ай · джей · кей · эл · эм · эн · оу · пи',
    why:'Эти буквы встречаются в именах, номерах и простых словах.',
    rule:'I — «ай», J — «джей». Они пишутся похоже на русские буквы, но называются иначе.',
    tip:'O звучит «оу», не русское «о».',
    build:['I','J','K','L','M','N','O','P'], practiceTitle:'Поставь буквы по порядку', practiceHint:'Нажимай буквы от I до P.',
    quiz:{q:'Как звучит буква J?',options:['джей','джи','йот'],answer:0,explain:'J называется «джей».'},
    outcome:'Ты отличаешь I от J и знаешь буквы I–P.'
  },
  {
    module:'МОДУЛЬ 1 · БУКВЫ И ЗВУКИ', title:'Алфавит: Q–Z', tag:'ОСНОВА',
    english:'Q, R, S, T, U, V, W, X, Y, Z.', meaning:'Последняя часть английского алфавита.',
    pronounce:'кью · ар · эс · ти · ю · ви · дабл-ю · экс · уай · зи',
    why:'Теперь можно продиктовать имя и понимать английские буквы в коде.',
    rule:'В американском английском Z называют «зи». W — «дабл-ю».',
    tip:'Q почти всегда идёт рядом с U: question, quick.',
    build:['Q','R','S','T','U','V','W','X','Y','Z'], practiceTitle:'Поставь буквы по порядку', practiceHint:'Нажимай буквы от Q до Z.',
    quiz:{q:'Как называется буква W?',options:['дабл-ю','ви','дубль-вэ'],answer:0,explain:'W называется «дабл-ю».'},
    outcome:'Ты закончил алфавит и знаешь, как называются все 26 букв.'
  },
  {
    module:'МОДУЛЬ 1 · БУКВЫ И ЗВУКИ', title:'Короткие гласные', tag:'ЧТЕНИЕ',
    english:'cat · bed · sit · cup', meaning:'cat — кошка; bed — кровать; sit — сидеть; cup — чашка.',
    pronounce:'cat — кэт · bed — бэд · sit — короткое сит · cup — кап',
    why:'Ты начинаешь не угадывать английские слова, а слышать, как гласные меняют смысл.',
    rule:'В коротких словах буква гласной часто даёт короткий звук. a в cat не русское «а»; i в sit не длинное «ии».',
    tip:'Русская запись — только подсказка. Сначала слушай, затем смотри на движение рта и повторяй.',
    practiceType:'sound', practiceTitle:'Подбери звук к слову', practiceHint:'Сначала прочитай слово, затем выбери, какой звук в нём главный.',
    soundItems:[
      {word:'cat',meaning:'кошка',options:['a — звук /æ/','e — звук /e/','i — звук /ɪ/'],answer:0},
      {word:'bed',meaning:'кровать',options:['i — звук /ɪ/','e — звук /e/','u — звук /ʌ/'],answer:1},
      {word:'sit',meaning:'сидеть',options:['a — звук /æ/','i — звук /ɪ/','e — звук /e/'],answer:1},
      {word:'cup',meaning:'чашка',options:['u — звук /ʌ/','a — звук /æ/','i — звук /ɪ/'],answer:0}
    ],
    quiz:{q:'Как ближе всего звучит cat?',options:['кэт','кат','кит'],answer:0,explain:'В cat буква a даёт звук /æ/, он ближе к «э», но рот открывается шире.'},
    outcome:'Ты знаешь: буква и звук — разные вещи, и слышишь четыре короткие гласные.'
  },
  {
    module:'МОДУЛЬ 1 · БУКВЫ И ЗВУКИ', title:'Звук TH: think и thank', tag:'ПРОИЗНОШЕНИЕ',
    english:'think · thank · three', meaning:'думать · спасибо · три',
    pronounce:'язык чуть между зубами + воздух: θинк · θэнк · θри',
    why:'TH — звук, которого нет в русском. Если понять положение языка, тебя легче понять.',
    rule:'Для TH в этих словах кончик языка слегка выходит между зубами. Воздух идёт вперёд. Это не «с», не «з» и не «в».',
    tip:'Положи руку перед ртом: на TH должен чувствоваться воздух. Тренируй медленно перед зеркалом.',
    practiceType:'sound', practiceTitle:'Выбери правильное движение', practiceHint:'Выбери, как нужно сделать звук в начале think.',
    soundItems:[
      {word:'think',meaning:'думать',options:['язык чуть между зубами, воздух вперёд','как русское «с»','как русское «в»'],answer:0}
    ],
    quiz:{q:'Как НЕ надо заменять TH в think?',options:['на русское «с»','язык между зубами и воздух','медленно повторить перед зеркалом'],answer:0,explain:'TH не равно русскому «с». Сначала поставь язык и выпусти воздух.'},
    outcome:'Ты знаешь положение рта для TH и можешь отдельно тренировать think и thank.'
  },
  {
    module:'МОДУЛЬ 1 · БУКВЫ И ЗВУКИ', title:'Звук W: we want water', tag:'ПРОИЗНОШЕНИЕ',
    english:'We want water.', meaning:'Мы хотим воды.',
    pronounce:'уи уонт уотэр',
    why:'W часто русскоговорящие заменяют на «в». Эта короткая фраза помогает поставить звук.',
    rule:'W начинается с округлённых губ, как очень короткое «у», но без русского звука «в».',
    tip:'Сначала сделай губы трубочкой, потом сразу переходи к следующему звуку: we, want, water.',
    build:['We','want','water'],practiceTitle:'Собери фразу',practiceHint:'Собери слова в обычном английском порядке.',
    quiz:{q:'Как начинается звук W в слове we?',options:['губы трубочкой, без «в»','как русское «в»','как «ф»'],answer:0,explain:'W начинается губами, а не зубами: короткое «у» без русского «в».'},
    outcome:'Ты умеешь отличать W от русского «в» в короткой фразе.'
  },
  {
    module:'МОДУЛЬ 2 · ПЕРВЫЕ ФРАЗЫ', title:'Знакомство: Hello, I’m…', tag:'ЗНАКОМСТВО',
    english:'Hello, I’m Rustam.', meaning:'Привет, я Рустам.',
    pronounce:'хэлоу · айм Рустам',
    why:'Это первая безопасная фраза при знакомстве с человеком.',
    rule:'I’m — сокращение от I am. В этой фразе I’m означает «я».',
    tip:'Hello — не русское «хелло»: слушай связку целиком «хэлоу».',
    build:['Hello','I’m','Rustam'],practiceTitle:'Собери фразу',practiceHint:'Сначала приветствие, потом «я», затем имя.',
    quiz:{q:'Что означает I’m?',options:['я','ты','привет'],answer:0,explain:'I’m = I am. В знакомстве это «я».'},
    outcome:'Ты можешь поздороваться и представиться.'
  },
  {
    module:'МОДУЛЬ 2 · ПЕРВЫЕ ФРАЗЫ', title:'Как дела? Как ответить?', tag:'РАЗГОВОР',
    english:'How are you? I’m fine, thanks.', meaning:'Как дела? Хорошо, спасибо.',
    pronounce:'хау ар ю · айм файн сэнкс',
    why:'Это самый частый короткий обмен после приветствия.',
    rule:'How are you? — готовый вопрос «Как дела?». В английском вопрос начинается с How, затем are, затем you.',
    tip:'Не переводи слово за словом. Запомни первую связку целиком.',
    build:['How','are','you'],practiceTitle:'Собери вопрос',practiceHint:'Вопрос начинается с How, затем are, затем you.',
    quiz:{q:'Как коротко ответить «Хорошо, спасибо»?',options:['I’m fine, thanks.','How you?','I am name.'],answer:0,explain:'I’m fine, thanks. — короткий естественный ответ.'},
    outcome:'Ты можешь начать короткий диалог: спросить и ответить.'
  },
  {
    module:'МОДУЛЬ 2 · ПЕРВЫЕ ФРАЗЫ', title:'Мне нужна помощь', tag:'ПРОСЬБА',
    english:'I need some help.', meaning:'Мне нужна помощь.',
    pronounce:'ай нид сам хелп',
    why:'Фраза нужна в дороге, магазине, отеле и любом новом месте.',
    rule:'I — «я». Need — «нуждаться». В английском сначала обычно говорят, кто делает действие.',
    tip:'В help короткий звук: «хелп», не «хииилп».',
    build:['I','need','some','help'],practiceTitle:'Собери фразу',practiceHint:'Сначала «я», затем что тебе нужно.',
    quiz:{q:'Что означает need?',options:['нуждаться','идти','помнить'],answer:0,explain:'Need означает «нуждаться».'},
    outcome:'Ты умеешь попросить помощь простой понятной фразой.'
  },
  {
    module:'МОДУЛЬ 2 · ПЕРВЫЕ ФРАЗЫ', title:'Где находится…?', tag:'ДОРОГА',
    english:'Where is the station?', meaning:'Где находится станция?',
    pronounce:'уэр из зэ стейшн',
    why:'С этой схемой можно спросить дорогу к любому месту.',
    rule:'Where is + место? — «Где находится + место?». Сначала вопросительное слово Where, потом is.',
    tip:'The здесь ближе к «зэ», но язык всё равно касается зубов.',
    build:['Where','is','the','station'],practiceTitle:'Собери вопрос',practiceHint:'Сначала Where, затем is, затем место.',
    quiz:{q:'Какое слово означает «где»?',options:['Where','What','When'],answer:0,explain:'Where означает «где».'},
    outcome:'Ты умеешь спросить дорогу к месту.'
  },
  {
    module:'МОДУЛЬ 2 · ПЕРВЫЕ ФРАЗЫ', title:'Вежливый заказ', tag:'КАФЕ',
    english:'I would like water.', meaning:'Я хотел бы воды.',
    pronounce:'ай вуд лайк уотэр',
    why:'Так вежливо просят в кафе, магазине или отеле.',
    rule:'I would like — мягкое «я бы хотел». Это вежливее, чем прямое I want.',
    tip:'Не проглатывай would на старте: говори медленно, потом ускоришься.',
    build:['I','would','like','water'],practiceTitle:'Собери вежливую просьбу',practiceHint:'Начни с I, затем would like и предмет.',
    quiz:{q:'Какая фраза звучит вежливее?',options:['I would like…','I want…','You order…'],answer:0,explain:'I would like… — вежливое «я бы хотел».'},
    outcome:'Ты умеешь вежливо попросить нужную вещь.'
  },
  {
    module:'МОДУЛЬ 3 · ЗАКРЕПЛЕНИЕ', title:'Закрепление: я и помощь', tag:'ЗАКРЕПЛЕНИЕ',
    english:'Hello. I’m Rustam. I need some help.', meaning:'Привет. Я Рустам. Мне нужна помощь.',
    pronounce:'хэлоу · айм Рустам · ай нид сам хелп',
    why:'Закрепляем не память карточек, а умение коротко представиться и попросить помощь.',
    rule:'Английская фраза чаще идёт так: кто? → что делает / что ему нужно. I → need → help.',
    tip:'Если запутался, вернись к урокам 4–9. Повторение — часть обучения, а не ошибка.',
    build:['Hello','I’m','Rustam','I','need','some','help'],practiceTitle:'Собери две короткие фразы',practiceHint:'Сначала: Hello, I’m Rustam. Затем: I need some help.',
    quiz:{q:'Как правильно сказать: «Привет, я Рустам. Мне нужна помощь»?',options:['Hello. I’m Rustam. I need some help.','Hello. I Rustam need help some.','I’m help. Hello Rustam.'],answer:0,explain:'Сначала приветствие и имя, затем отдельная фраза о том, что тебе нужна помощь.'},
    outcome:'Ты прошёл старт: знаешь алфавит, ключевые звуки и можешь представиться или попросить помощь.'
  }
  ,
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Кто говорит: I, you, we, they', tag:'МЕСТОИМЕНИЯ',
    english:'We are ready.', meaning:'Мы готовы.',
    pronounce:'уи ар рэди',
    why:'Чтобы сказать о себе, собеседнике или группе, сначала нужно назвать того, о ком говорим.',
    rule:'I — я, you — ты/вы, we — мы, they — они. В английском местоимение обычно стоит первым.',
    tip:'You может означать и «ты», и «вы». Смысл понятен из ситуации.',
    build:['We','are','ready'],practiceTitle:'Собери фразу',practiceHint:'Сначала кто, затем состояние: we → are → ready.',
    quiz:{q:'Как по-английски «мы»?',options:['we','they','you'],answer:0,explain:'We означает «мы».'},
    outcome:'Ты умеешь назвать, кто говорит или о ком идёт речь.'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Связка am / are', tag:'ГРАММАТИКА',
    english:'I am ready. You are welcome.', meaning:'Я готов. Пожалуйста / Добро пожаловать.',
    pronounce:'ай эм рэди · ю ар уэлкам',
    why:'В русском мы часто не говорим «есть», а в английском в таких фразах нужна связка am или are.',
    rule:'После I ставим am. После you, we, they ставим are. Нельзя сказать I ready.',
    tip:'В разговоре I am часто сокращают до I’m: I’m ready.',
    build:['I','am','ready'],practiceTitle:'Собери фразу',practiceHint:'После I обязательно поставь am.',
    quiz:{q:'Как правильно?',options:['I am ready.','I are ready.','I ready.'],answer:0,explain:'После I нужна связка am: I am ready.'},
    outcome:'Ты понимаешь, зачем в английском нужны am и are.'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Связка is', tag:'ГРАММАТИКА',
    english:'This is my phone.', meaning:'Это мой телефон.',
    pronounce:'зис из май фоун',
    why:'Так можно показать предмет, человека или место и сказать, что это такое.',
    rule:'После he, she, it и this ставим is. This is — «это есть». В русской речи слово «есть» обычно не слышно, в английской конструкции оно нужно.',
    tip:'This начинается со звонкого TH: язык слегка между зубами, голос включён.',
    build:['This','is','my','phone'],practiceTitle:'Собери фразу',practiceHint:'Сначала покажи предмет: this, затем is.',
    quiz:{q:'Что ставим после this?',options:['is','are','am'],answer:0,explain:'This — это один предмет, поэтому this is.'},
    outcome:'Ты можешь показать предмет и сказать: «Это мой…».'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Порядок слов', tag:'ПРАВИЛО',
    english:'I work here.', meaning:'Я работаю здесь.',
    pronounce:'ай уорк хиэр',
    why:'Русский позволяет менять слова местами. В английском порядок помогает сразу понять смысл.',
    rule:'В простом утверждении: кто? → что делает? → остальное. I → work → here.',
    tip:'Сначала найди «кто?», потом действие. Не переводь русское предложение перестановкой слов.',
    build:['I','work','here'],practiceTitle:'Поставь слова по порядку',practiceHint:'Кто? → действие → где?',
    quiz:{q:'Какой порядок верный?',options:['I work here.','Work I here.','Here I work?'],answer:0,explain:'В обычном утверждении сначала идёт тот, кто действует: I work here.'},
    outcome:'Ты знаешь базовый порядок слов в простом утверждении.'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Отрицание: I do not…', tag:'ОТРИЦАНИЕ',
    english:'I do not understand.', meaning:'Я не понимаю.',
    pronounce:'ай ду нот андэрстэнд',
    why:'Эта фраза спасает, когда человек говорит слишком быстро или ты не понял вопрос.',
    rule:'Для простого действия с I / you / we / they отрицание строится через do not: I do not understand. В разговоре: I don’t understand.',
    tip:'Не говори I not understand. Нужен помощник do.',
    build:['I','do','not','understand'],practiceTitle:'Собери отрицание',practiceHint:'Кто? → do not → действие.',
    quiz:{q:'Как правильно сказать «Я не понимаю»?',options:['I do not understand.','I not understand.','I am not understand.'],answer:0,explain:'С действием understand используем do not: I do not understand.'},
    outcome:'Ты умеешь спокойно сказать, что не понял.'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Вопрос: Do you…?', tag:'ВОПРОС',
    english:'Do you speak English?', meaning:'Вы говорите по-английски?',
    pronounce:'ду ю спик инглиш',
    why:'Так можно уточнить, сможет ли человек поговорить с тобой на английском.',
    rule:'В вопросе с действием do выходит вперёд: Do → you → speak? Это не русская интонация, а порядок слов.',
    tip:'В ответе можно сказать: Yes, I do. / No, I don’t.',
    build:['Do','you','speak','English'],practiceTitle:'Собери вопрос',practiceHint:'Вопрос начинается с Do.',
    quiz:{q:'С чего начинается этот вопрос?',options:['Do','You','Speak'],answer:0,explain:'Вопрос к действию начинается с Do: Do you speak English?'},
    outcome:'Ты можешь задать простой вопрос с Do you…?'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Один предмет: a / an', tag:'АРТИКЛИ',
    english:'I need a ticket.', meaning:'Мне нужен билет.',
    pronounce:'ай нид э тикит',
    why:'В английском перед одним предметом часто ставят короткое слово a или an.',
    rule:'A означает «один / какой-то» перед согласным звуком: a ticket. An — перед гласным звуком: an apple.',
    tip:'Не пытайся переводить a каждый раз. Сначала замечай его как часть английской фразы.',
    build:['I','need','a','ticket'],practiceTitle:'Собери просьбу',practiceHint:'После need назови один предмет с a.',
    quiz:{q:'Как правильно?',options:['a ticket','an ticket','ticket a'],answer:0,explain:'Ticket начинается с согласного звука, поэтому a ticket.'},
    outcome:'Ты знаешь, зачем нужен a перед одним предметом.'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Этот и тот: this / that', tag:'УКАЗАНИЕ',
    english:'This is a ticket. That is my bag.', meaning:'Это билет. То — моя сумка.',
    pronounce:'зис из э тикит · зэт из май бэг',
    why:'Эти слова помогают показать предмет рядом или чуть дальше.',
    rule:'This — это рядом. That — то дальше. После обоих в простой фразе ставим is.',
    tip:'В this и that есть TH: не заменяй его русским «з».',
    build:['This','is','a','ticket'],practiceTitle:'Собери фразу',practiceHint:'Рядом с тобой: this → is → a ticket.',
    quiz:{q:'Что выбираем для предмета рядом?',options:['this','that','they'],answer:0,explain:'This — «это» рядом. That — «то» дальше.'},
    outcome:'Ты умеешь показать предмет: this или that.'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Когда предметов много', tag:'МНОЖЕСТВЕННОЕ ЧИСЛО',
    english:'Two tickets, please.', meaning:'Два билета, пожалуйста.',
    pronounce:'ту тикитс плиз',
    why:'Числа и множественное число нужны в магазине, на вокзале и в кафе.',
    rule:'После two и других чисел предмет обычно получает -s: two tickets. Один билет — one ticket.',
    tip:'В tickets в конце слышится короткий звук «с»: ticket-s.',
    build:['Two','tickets','please'],practiceTitle:'Собери просьбу',practiceHint:'Сначала число, затем предмет во множественном числе.',
    quiz:{q:'Как правильно сказать «два билета»?',options:['two tickets','two ticket','tickets two'],answer:0,explain:'После two добавляем -s: two tickets.'},
    outcome:'Ты можешь попросить несколько одинаковых предметов.'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Цена: How much is it?', tag:'МАГАЗИН',
    english:'How much is it?', meaning:'Сколько это стоит?',
    pronounce:'хау мач из ит',
    why:'Это одна из самых полезных фраз в магазине, кафе и на рынке.',
    rule:'How much — «сколько». Is it — «это стоит / это есть». Вопрос уже готовый: не переставляй слова.',
    tip:'Сохрани фразу целиком, как номер телефона: How much is it?',
    build:['How','much','is','it'],practiceTitle:'Собери вопрос о цене',practiceHint:'Начни с How much, затем is it.',
    quiz:{q:'Что означает How much?',options:['сколько','где','который час'],answer:0,explain:'How much означает «сколько», чаще всего о цене или количестве.'},
    outcome:'Ты можешь спросить цену.'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Время: What time is it?', tag:'ВРЕМЯ',
    english:'What time is it?', meaning:'Который час?',
    pronounce:'уот тайм из ит',
    why:'Фраза нужна, когда ты ждёшь транспорт, встречу или хочешь понять расписание.',
    rule:'What time — «который час». В английском вопросе связка is идёт перед it: What time is it?',
    tip:'Time читается «тайм», буква i здесь даёт другой звук — это нормально: буква и звук не всегда совпадают.',
    build:['What','time','is','it'],practiceTitle:'Собери вопрос о времени',practiceHint:'What time → is → it.',
    quiz:{q:'Как спросить «Который час?»',options:['What time is it?','What is time it?','Time what is it?'],answer:0,explain:'Готовая английская конструкция: What time is it?'},
    outcome:'Ты можешь спросить время и узнаёшь эту конструкцию на слух.'
  },
  {
    module:'МОДУЛЬ 4 · ОСНОВА ГРАММАТИКИ', title:'Мини-диалог: билет и помощь', tag:'ПОВТОРЕНИЕ',
    english:'Hello. I need two tickets, please.', meaning:'Здравствуйте. Мне нужно два билета, пожалуйста.',
    pronounce:'хэлоу · ай нид ту тикитс плиз',
    why:'Это короткая настоящая ситуация: поздороваться, назвать потребность и количество.',
    rule:'Собираем известную схему: кто? → действие → число + предмет → please. Английский порядок не меняем.',
    tip:'Не надо говорить идеально. Сначала передай смысл: I need two tickets, please.',
    build:['Hello','I','need','two','tickets','please'],practiceTitle:'Собери реальную просьбу',practiceHint:'Приветствие → кто → действие → сколько и что → please.',
    quiz:{q:'Как правильно попросить два билета?',options:['I need two tickets, please.','I two tickets need, please.','Need I tickets two.'],answer:0,explain:'В английском сначала I, затем need, потом two tickets.'},
    outcome:'Ты применил правила в настоящей просьбе и готов к модулю «Город и поездка».'
  }
];


window.SAYGO_LESSONS.push(
{module:'МОДУЛЬ 5 · ГОРОД И ПОЕЗДКА',title:'Где автобус?',tag:'ГОРОД',english:'Where is the bus stop?',meaning:'Где автобусная остановка?',pronounce:'уэр из зэ бас стоп',why:'Помогает найти транспорт в незнакомом городе.',rule:'Where is + место? — готовая схема вопроса.',tip:'Запомни bus stop целиком: автобусная остановка.',build:['Where','is','the','bus','stop'],practiceTitle:'Собери вопрос',practiceHint:'Where → is → the → место.',quiz:{q:'Что означает bus stop?',options:['автобусная остановка','вокзал','билет'],answer:0,explain:'Bus stop — место, где останавливается автобус.'},outcome:'Ты умеешь спросить, где остановка.'},
{module:'МОДУЛЬ 5 · ГОРОД И ПОЕЗДКА',title:'Направление: left / right',tag:'ДОРОГА',english:'Turn left, please.',meaning:'Поверните налево, пожалуйста.',pronounce:'тёрн лэфт плиз',why:'Нужно понять или дать простое направление.',rule:'Turn — повернуть. Left — налево, right — направо.',tip:'Please делает просьбу вежливее.',build:['Turn','left','please'],practiceTitle:'Собери просьбу',practiceHint:'Действие → направление → please.',quiz:{q:'Что значит right?',options:['направо','налево','прямо'],answer:0,explain:'Right — направо.'},outcome:'Ты понимаешь простые направления.'},
{module:'МОДУЛЬ 5 · ГОРОД И ПОЕЗДКА',title:'Мне нужен такси',tag:'ТРАНСПОРТ',english:'I need a taxi.',meaning:'Мне нужно такси.',pronounce:'ай нид э тэкси',why:'Нужно быстро объяснить свою потребность.',rule:'I need + a + предмет — мне нужен один предмет или сервис.',tip:'Taxi — такси; перед ним здесь a.',build:['I','need','a','taxi'],practiceTitle:'Собери просьбу',practiceHint:'I → need → a → taxi.',quiz:{q:'Какой артикль перед taxi?',options:['a','an','не нужен'],answer:0,explain:'Taxi начинается с согласного звука: a taxi.'},outcome:'Ты умеешь попросить такси.'},
{module:'МОДУЛЬ 5 · ГОРОД И ПОЕЗДКА',title:'У меня есть бронь',tag:'ОТЕЛЬ',english:'I have a reservation.',meaning:'У меня есть бронь.',pronounce:'ай хэв э рэзэрвейшн',why:'Базовая фраза при заселении.',rule:'I have — «у меня есть». После have называем то, что есть.',tip:'Reservation можно показать в телефоне, если сложно произнести.',build:['I','have','a','reservation'],practiceTitle:'Собери фразу',practiceHint:'Кто → have → что есть.',quiz:{q:'Что означает have?',options:['иметь','идти','хотеть'],answer:0,explain:'Have означает «иметь».'},outcome:'Ты можешь сказать, что у тебя есть бронь.'},
{module:'МОДУЛЬ 5 · ГОРОД И ПОЕЗДКА',title:'Номер комнаты',tag:'ОТЕЛЬ',english:'My room number is five.',meaning:'Номер моей комнаты — пять.',pronounce:'май рум намбэр из файв',why:'Нужно понять или назвать номер комнаты.',rule:'My — мой. Number is… — номер такой-то.',tip:'Five читается «файв», не «фив».',build:['My','room','number','is','five'],practiceTitle:'Собери фразу',practiceHint:'Мой предмет → is → номер.',quiz:{q:'Что означает my?',options:['мой','твой','их'],answer:0,explain:'My — мой / моя / моё.'},outcome:'Ты умеешь назвать номер комнаты.'},
{module:'МОДУЛЬ 5 · ГОРОД И ПОЕЗДКА',title:'Когда отправление?',tag:'ВРЕМЯ',english:'What time is the train?',meaning:'Во сколько поезд?',pronounce:'уот тайм из зэ трэйн',why:'Помогает уточнить время транспорта.',rule:'What time is + событие? — во сколько происходит?',tip:'Train — поезд; ai даёт звук «эй».',build:['What','time','is','the','train'],practiceTitle:'Собери вопрос',practiceHint:'What time → is → the → train.',quiz:{q:'Что значит train?',options:['поезд','самолёт','такси'],answer:0,explain:'Train — поезд.'},outcome:'Ты можешь спросить время поезда.'},
{module:'МОДУЛЬ 5 · ГОРОД И ПОЕЗДКА',title:'Поездка: мини-диалог',tag:'ПОВТОРЕНИЕ',english:'Hello. Where is the bus stop?',meaning:'Здравствуйте. Где остановка?',pronounce:'хэлоу · уэр из зэ бас стоп',why:'Соединяем приветствие и вопрос о дороге.',rule:'Сначала приветствие, затем готовый вопрос Where is…?',tip:'Не учи отдельные слова — скажи всю связку.',build:['Hello','Where','is','the','bus','stop'],practiceTitle:'Собери мини-диалог',practiceHint:'Приветствие → Where is → место.',quiz:{q:'Какая фраза просит найти остановку?',options:['Where is the bus stop?','I have a bus stop.','Bus stop is I.'],answer:0,explain:'Where is the bus stop? — «Где остановка?»'},outcome:'Ты можешь начать разговор и спросить дорогу.'},
{module:'МОДУЛЬ 6 · КАФЕ И ПОКУПКИ',title:'Меню, пожалуйста',tag:'КАФЕ',english:'A menu, please.',meaning:'Меню, пожалуйста.',pronounce:'э меню плиз',why:'Самая короткая вежливая просьба в кафе.',rule:'Можно назвать предмет и добавить please.',tip:'A здесь звучит очень коротко: «э».',build:['A','menu','please'],practiceTitle:'Собери просьбу',practiceHint:'Предмет → please.',quiz:{q:'Что просит человек?',options:['меню','счёт','воду'],answer:0,explain:'A menu, please. — «Меню, пожалуйста».'},outcome:'Ты умеешь вежливо попросить меню.'},
{module:'МОДУЛЬ 6 · КАФЕ И ПОКУПКИ',title:'Я хочу кофе',tag:'КАФЕ',english:'I would like coffee.',meaning:'Я хотел бы кофе.',pronounce:'ай вуд лайк кофи',why:'Вежливый заказ напитка.',rule:'I would like + предмет — вежливая просьба.',tip:'Не нужно a, когда говоришь о кофе как о напитке вообще.',build:['I','would','like','coffee'],practiceTitle:'Собери заказ',practiceHint:'I would like → напиток.',quiz:{q:'Какая просьба вежливая?',options:['I would like coffee.','Coffee I want.','You coffee.'],answer:0,explain:'I would like — вежливое «я бы хотел».'},outcome:'Ты можешь заказать кофе.'},
{module:'МОДУЛЬ 6 · КАФЕ И ПОКУПКИ',title:'Без сахара',tag:'КАФЕ',english:'No sugar, please.',meaning:'Без сахара, пожалуйста.',pronounce:'ноу шугэр плиз',why:'Помогает уточнить простой заказ.',rule:'No + предмет — «без / нет» этого предмета.',tip:'Sugar — сахар. Скажи фразу коротко и спокойно.',build:['No','sugar','please'],practiceTitle:'Собери уточнение',practiceHint:'No → предмет → please.',quiz:{q:'Что означает no sugar?',options:['без сахара','больше сахара','сладкий сахар'],answer:0,explain:'No sugar — без сахара.'},outcome:'Ты умеешь уточнить заказ.'},
{module:'МОДУЛЬ 6 · КАФЕ И ПОКУПКИ',title:'Счёт, пожалуйста',tag:'КАФЕ',english:'The bill, please.',meaning:'Счёт, пожалуйста.',pronounce:'зэ бил плиз',why:'Нужно закончить заказ в кафе.',rule:'The bill — конкретный счёт за твой заказ.',tip:'В США часто говорят check, но bill понятно везде.',build:['The','bill','please'],practiceTitle:'Собери просьбу',practiceHint:'The bill → please.',quiz:{q:'Что означает bill в кафе?',options:['счёт','билет','меню'],answer:0,explain:'Bill — счёт.'},outcome:'Ты умеешь попросить счёт.'},
{module:'МОДУЛЬ 6 · КАФЕ И ПОКУПКИ',title:'Это слишком дорого',tag:'МАГАЗИН',english:'It is too expensive.',meaning:'Это слишком дорого.',pronounce:'ит из ту экспэнсив',why:'Помогает вежливо отказаться или уточнить цену.',rule:'It is — «это». Too — слишком. Expensive — дорогой.',tip:'Не путай too («слишком») и two («два»): они звучат одинаково.',build:['It','is','too','expensive'],practiceTitle:'Собери фразу',practiceHint:'It is → оценка.',quiz:{q:'Что означает expensive?',options:['дорогой','дешёвый','быстрый'],answer:0,explain:'Expensive — дорогой.'},outcome:'Ты можешь сказать, что цена высокая.'},
{module:'МОДУЛЬ 6 · КАФЕ И ПОКУПКИ',title:'У вас есть…?',tag:'МАГАЗИН',english:'Do you have this?',meaning:'У вас есть это?',pronounce:'ду ю хэв зис',why:'В магазине можно показать вещь и задать вопрос.',rule:'Do you have…? — «У вас есть…?». Do идёт первым.',tip:'Покажи предмет или фото и скажи this.',build:['Do','you','have','this'],practiceTitle:'Собери вопрос',practiceHint:'Do → you → have → this.',quiz:{q:'Как начинается вопрос «У вас есть…?»',options:['Do you have…?','You have…?','Have you…?'],answer:0,explain:'В этой схеме вопрос начинается с Do.'},outcome:'Ты умеешь спросить о наличии товара.'},
{module:'МОДУЛЬ 6 · КАФЕ И ПОКУПКИ',title:'Другой размер',tag:'МАГАЗИН',english:'Do you have a larger size?',meaning:'У вас есть размер побольше?',pronounce:'ду ю хэв э ларджэр сайз',why:'Полезно при покупке одежды или обуви.',rule:'Larger — больше по размеру. Size — размер.',tip:'Если нужен меньше: a smaller size.',build:['Do','you','have','a','larger','size'],practiceTitle:'Собери вопрос',practiceHint:'Do you have → a → larger size.',quiz:{q:'Что означает size?',options:['размер','цена','цвет'],answer:0,explain:'Size — размер.'},outcome:'Ты можешь попросить другой размер.'},
{module:'МОДУЛЬ 6 · КАФЕ И ПОКУПКИ',title:'Оплата картой',tag:'ОПЛАТА',english:'Can I pay by card?',meaning:'Можно оплатить картой?',pronounce:'кэн ай пэй бай кард',why:'Нужно перед оплатой в магазине или кафе.',rule:'Can I…? — «могу я…?». После can действие без to.',tip:'Pay — платить, card — карта.',build:['Can','I','pay','by','card'],practiceTitle:'Собери вопрос',practiceHint:'Can → I → действие → способ.',quiz:{q:'Что означает pay?',options:['платить','покупать','показывать'],answer:0,explain:'Pay — платить.'},outcome:'Ты можешь спросить об оплате картой.'},
{module:'МОДУЛЬ 6 · КАФЕ И ПОКУПКИ',title:'Кафе: мини-диалог',tag:'ПОВТОРЕНИЕ',english:'I would like coffee, please.',meaning:'Я хотел бы кофе, пожалуйста.',pronounce:'ай вуд лайк кофи плиз',why:'Собираем полный вежливый заказ.',rule:'I would like → предмет → please.',tip:'Please в конце делает просьбу мягче.',build:['I','would','like','coffee','please'],practiceTitle:'Собери заказ',practiceHint:'Кто → вежливая просьба → напиток → please.',quiz:{q:'Какой порядок верный?',options:['I would like coffee, please.','Coffee I would like please.','Please coffee like I would.'],answer:0,explain:'Вежливый заказ начинается с I would like.'},outcome:'Ты можешь сделать короткий заказ в кафе.'},
{module:'МОДУЛЬ 7 · ОБЩЕНИЕ КАЖДЫЙ ДЕНЬ',title:'Я не знаю',tag:'ОБЩЕНИЕ',english:'I do not know.',meaning:'Я не знаю.',pronounce:'ай ду нот ноу',why:'Полезнее честно сказать, что не знаешь, чем молчать.',rule:'I do not + действие — простое отрицание.',tip:'В разговоре: I don’t know.',build:['I','do','not','know'],practiceTitle:'Собери фразу',practiceHint:'I → do not → know.',quiz:{q:'Какое слово означает «знать»?',options:['know','need','go'],answer:0,explain:'Know — знать.'},outcome:'Ты умеешь сказать, что не знаешь.'},
{module:'МОДУЛЬ 7 · ОБЩЕНИЕ КАЖДЫЙ ДЕНЬ',title:'Я понимаю',tag:'ОБЩЕНИЕ',english:'I understand.',meaning:'Я понимаю.',pronounce:'ай андэрстэнд',why:'Короткий ответ, когда объяснение стало ясным.',rule:'В утверждении после I сразу идёт действие: I understand.',tip:'Сравни с I do not understand: do появляется только в отрицании.',build:['I','understand'],practiceTitle:'Собери ответ',practiceHint:'Кто → действие.',quiz:{q:'Как сказать «Я понимаю»?',options:['I understand.','I do understand not.','I am understand.'],answer:0,explain:'В простом утверждении: I understand.'},outcome:'Ты отличаешь утверждение от отрицания.'},
{module:'МОДУЛЬ 7 · ОБЩЕНИЕ КАЖДЫЙ ДЕНЬ',title:'Повторите, пожалуйста',tag:'ОБЩЕНИЕ',english:'Please say that again.',meaning:'Повторите это, пожалуйста.',pronounce:'плиз сэй зэт эгэн',why:'Нужно, когда фразу сказали слишком быстро.',rule:'Please + действие — вежливая просьба. Again — снова.',tip:'That — «это», здесь произноси звонкий TH.',build:['Please','say','that','again'],practiceTitle:'Собери просьбу',practiceHint:'Please → say → that → again.',quiz:{q:'Что означает again?',options:['снова','медленнее','завтра'],answer:0,explain:'Again — снова.'},outcome:'Ты умеешь попросить повторить.'},
{module:'МОДУЛЬ 7 · ОБЩЕНИЕ КАЖДЫЙ ДЕНЬ',title:'Говорите медленнее',tag:'ОБЩЕНИЕ',english:'Please speak slowly.',meaning:'Говорите медленнее, пожалуйста.',pronounce:'плиз спик слоули',why:'Фраза помогает продолжить разговор, а не сдаться.',rule:'Speak — говорить. Slowly — медленно.',tip:'Сначала выучи фразу целиком.',build:['Please','speak','slowly'],practiceTitle:'Собери просьбу',practiceHint:'Please → действие → как.',quiz:{q:'Что означает slowly?',options:['медленно','громко','снова'],answer:0,explain:'Slowly — медленно.'},outcome:'Ты умеешь попросить говорить медленнее.'},
{module:'МОДУЛЬ 7 · ОБЩЕНИЕ КАЖДЫЙ ДЕНЬ',title:'Я напишу тебе',tag:'СООБЩЕНИЯ',english:'I will text you.',meaning:'Я напишу тебе.',pronounce:'ай уил текст ю',why:'Полезно закончить разговор и договориться о связи.',rule:'I will + действие — «я буду / я сделаю».',tip:'Will часто звучит коротко: «уил».',build:['I','will','text','you'],practiceTitle:'Собери обещание',practiceHint:'I → will → действие → кому.',quiz:{q:'Что здесь означает will?',options:['буду / сделаю','не хочу','могу'],answer:0,explain:'Will показывает будущее действие.'},outcome:'Ты можешь сказать, что напишешь человеку.'},
{module:'МОДУЛЬ 7 · ОБЩЕНИЕ КАЖДЫЙ ДЕНЬ',title:'Увидимся завтра',tag:'ПЛАНЫ',english:'See you tomorrow.',meaning:'Увидимся завтра.',pronounce:'си ю тэмороу',why:'Естественное завершение разговора.',rule:'See you — «увидимся». Tomorrow — завтра.',tip:'Это готовая фраза: не добавляй I.',build:['See','you','tomorrow'],practiceTitle:'Собери прощание',practiceHint:'See → you → tomorrow.',quiz:{q:'Что означает tomorrow?',options:['завтра','сегодня','вчера'],answer:0,explain:'Tomorrow — завтра.'},outcome:'Ты умеешь договориться о встрече завтра.'},
{module:'МОДУЛЬ 7 · ОБЩЕНИЕ КАЖДЫЙ ДЕНЬ',title:'Мне плохо',tag:'САМОЧУВСТВИЕ',english:'I do not feel well.',meaning:'Я плохо себя чувствую.',pronounce:'ай ду нот фил уэл',why:'Важно суметь объяснить своё состояние.',rule:'Feel well — хорошо себя чувствовать. Отрицание: do not feel well.',tip:'Если нужна помощь, добавь: I need help.',build:['I','do','not','feel','well'],practiceTitle:'Собери фразу',practiceHint:'I → do not → feel → well.',quiz:{q:'Что означает feel well?',options:['хорошо себя чувствовать','хорошо говорить','хорошо платить'],answer:0,explain:'Feel well — хорошо себя чувствовать.'},outcome:'Ты можешь сообщить о плохом самочувствии.'},
{module:'МОДУЛЬ 7 · ОБЩЕНИЕ КАЖДЫЙ ДЕНЬ',title:'Общение: мини-диалог',tag:'ПОВТОРЕНИЕ',english:'I do not understand. Please speak slowly.',meaning:'Я не понимаю. Пожалуйста, говорите медленнее.',pronounce:'ай ду нот андэрстэнд · плиз спик слоули',why:'Это готовый ответ в реальном разговоре.',rule:'Сначала честно говорим проблему, затем вежливо просим решение.',tip:'Скажи две короткие фразы с паузой.',build:['I','do','not','understand','Please','speak','slowly'],practiceTitle:'Собери ответ',practiceHint:'Проблема → просьба.',quiz:{q:'Что нужно сказать после «I do not understand»?',options:['Please speak slowly.','I am ticket.','How much tomorrow?'],answer:0,explain:'После проблемы просим говорить медленнее.'},outcome:'Ты умеешь не теряться, если не понял речь.'},
{module:'МОДУЛЬ 8 · РАБОТА И СЕРВИСЫ',title:'Я работаю здесь',tag:'РАБОТА',english:'I work here.',meaning:'Я работаю здесь.',pronounce:'ай уорк хиэр',why:'Коротко рассказать о себе на работе или в сервисе.',rule:'I → work → here: кто, действие, где.',tip:'Here — здесь.',build:['I','work','here'],practiceTitle:'Собери фразу',practiceHint:'Кто → действие → где.',quiz:{q:'Что означает here?',options:['здесь','там','сейчас'],answer:0,explain:'Here — здесь.'},outcome:'Ты умеешь сказать, где работаешь.'},
{module:'МОДУЛЬ 8 · РАБОТА И СЕРВИСЫ',title:'Мне нужна ваша помощь',tag:'РАБОТА',english:'I need your help.',meaning:'Мне нужна ваша помощь.',pronounce:'ай нид йор хелп',why:'Вежливая просьба к коллеге или сотруднику.',rule:'Your — ваш / твой. После need называем то, что нужно.',tip:'Your произноси слитно: «йор».',build:['I','need','your','help'],practiceTitle:'Собери просьбу',practiceHint:'I need → your → help.',quiz:{q:'Что означает your?',options:['ваш / твой','мой','их'],answer:0,explain:'Your — ваш или твой.'},outcome:'Ты умеешь попросить помощь у человека.'},
{module:'МОДУЛЬ 8 · РАБОТА И СЕРВИСЫ',title:'У меня проблема',tag:'СЕРВИС',english:'I have a problem.',meaning:'У меня проблема.',pronounce:'ай хэв э проблем',why:'Нужно начать объяснение сотруднику или поддержке.',rule:'I have a… — «у меня есть…».',tip:'После этого добавь простое объяснение или покажи экран.',build:['I','have','a','problem'],practiceTitle:'Собери фразу',practiceHint:'I → have → a → problem.',quiz:{q:'Что означает problem?',options:['проблема','вопрос','билет'],answer:0,explain:'Problem — проблема.'},outcome:'Ты можешь сообщить о проблеме.'},
{module:'МОДУЛЬ 8 · РАБОТА И СЕРВИСЫ',title:'Можете помочь?',tag:'СЕРВИС',english:'Can you help me?',meaning:'Вы можете мне помочь?',pronounce:'кэн ю хелп ми',why:'Прямая и вежливая просьба о помощи.',rule:'Can you + действие? — «Вы можете…?»',tip:'Me — мне; не путай с my — мой.',build:['Can','you','help','me'],practiceTitle:'Собери вопрос',practiceHint:'Can → you → help → me.',quiz:{q:'Что означает me?',options:['мне','мой','мы'],answer:0,explain:'Me — мне / меня.'},outcome:'Ты умеешь спросить, могут ли тебе помочь.'},
{module:'МОДУЛЬ 8 · РАБОТА И СЕРВИСЫ',title:'Я здесь впервые',tag:'ЗНАКОМСТВО',english:'I am here for the first time.',meaning:'Я здесь впервые.',pronounce:'ай эм хиэр фор зэ фёрст тайм',why:'Помогает объяснить, почему нужна подсказка.',rule:'I am + обстоятельство. For the first time — впервые.',tip:'Не обязательно запоминать каждое слово: учи связку целиком.',build:['I','am','here','for','the','first','time'],practiceTitle:'Собери фразу',practiceHint:'I am → here → for the first time.',quiz:{q:'Что означает first time?',options:['первый раз','вовремя','сейчас'],answer:0,explain:'First time — первый раз.'},outcome:'Ты можешь сказать, что пришёл впервые.'},
{module:'МОДУЛЬ 8 · РАБОТА И СЕРВИСЫ',title:'Давайте начнём',tag:'РАБОТА',english:'Let us get started.',meaning:'Давайте начнём.',pronounce:'лет ас гет стартед',why:'Уместно перед встречей, задачей или разговором.',rule:'Let us — давайте. В речи часто: Let’s.',tip:'Можно говорить Let’s get started.',build:['Let','us','get','started'],practiceTitle:'Собери фразу',practiceHint:'Let us → get started.',quiz:{q:'Что означает Let us?',options:['давайте','я хочу','вы можете'],answer:0,explain:'Let us — «давайте».'},outcome:'Ты умеешь предложить начать.'},
{module:'МОДУЛЬ 8 · РАБОТА И СЕРВИСЫ',title:'Я отправил сообщение',tag:'СООБЩЕНИЯ',english:'I sent a message.',meaning:'Я отправил сообщение.',pronounce:'ай сэнт э мэсидж',why:'Полезно в переписке и при уточнении задачи.',rule:'Sent — форма прошедшего времени от send: отправил.',tip:'Не учи сейчас все времена: запомни эту готовую рабочую фразу.',build:['I','sent','a','message'],practiceTitle:'Собери фразу',practiceHint:'I → sent → a message.',quiz:{q:'Что означает sent?',options:['отправил','получил','пишу'],answer:0,explain:'Sent — отправил.'},outcome:'Ты можешь сказать, что уже отправил сообщение.'},
{module:'МОДУЛЬ 8 · РАБОТА И СЕРВИСЫ',title:'Когда встреча?',tag:'РАБОТА',english:'What time is the meeting?',meaning:'Во сколько встреча?',pronounce:'уот тайм из зэ митинг',why:'Нужно уточнить время созвона или встречи.',rule:'What time is + событие? — во сколько событие?',tip:'Meeting — встреча / совещание.',build:['What','time','is','the','meeting'],practiceTitle:'Собери вопрос',practiceHint:'What time → is → the meeting.',quiz:{q:'Что означает meeting?',options:['встреча','билет','магазин'],answer:0,explain:'Meeting — встреча.'},outcome:'Ты умеешь спросить время встречи.'},
{module:'МОДУЛЬ 8 · РАБОТА И СЕРВИСЫ',title:'Работа: мини-диалог',tag:'ПОВТОРЕНИЕ',english:'Hello. I have a problem. Can you help me?',meaning:'Здравствуйте. У меня проблема. Вы можете помочь?',pronounce:'хэлоу · ай хэв э проблем · кэн ю хелп ми',why:'Соединяем приветствие, проблему и просьбу.',rule:'Сначала обозначь проблему, затем задай простой вопрос Can you…?',tip:'Это три короткие фразы — говори с паузой.',build:['Hello','I','have','a','problem','Can','you','help','me'],practiceTitle:'Собери рабочий диалог',practiceHint:'Приветствие → проблема → просьба.',quiz:{q:'Как вежливо попросить помощь?',options:['Can you help me?','You help I.','Help can me?'],answer:0,explain:'Can you help me? — понятная вежливая просьба.'},outcome:'Ты можешь начать простой разговор в сервисе или на работе.'},
{module:'МОДУЛЬ 9 · ЗАКРЕПЛЕНИЕ',title:'Повторение: город и кафе',tag:'ПОВТОРЕНИЕ',english:'Where is the bus stop? I would like coffee.',meaning:'Где остановка? Я хотел бы кофе.',pronounce:'уэр из зэ бас стоп · ай вуд лайк кофи',why:'Проверяем, что фразы работают в разных ситуациях.',rule:'Один и тот же порядок слов переносится из урока в урок.',tip:'Если запутался, повтори тему, а не угадывай.',build:['Where','is','the','bus','stop'],practiceTitle:'Собери вопрос',practiceHint:'Where is → место.',quiz:{q:'Как вежливо заказать кофе?',options:['I would like coffee.','Coffee I need would.','Would coffee I.'],answer:0,explain:'I would like coffee. — вежливый заказ.'},outcome:'Ты закрепил фразы для города и кафе.'},
{module:'МОДУЛЬ 9 · ЗАКРЕПЛЕНИЕ',title:'Повторение: разговор',tag:'ПОВТОРЕНИЕ',english:'I do not understand. Please say that again.',meaning:'Я не понимаю. Повторите, пожалуйста.',pronounce:'ай ду нот андэрстэнд · плиз сэй зэт эгэн',why:'Это ключевая связка, чтобы продолжать разговор.',rule:'Отрицание через do not + вежливая просьба.',tip:'Лучше сказать эту фразу, чем просто кивнуть.',build:['I','do','not','understand','Please','say','that','again'],practiceTitle:'Собери ответ',practiceHint:'Проблема → просьба повторить.',quiz:{q:'Что просим в конце?',options:['повторить','оплатить','повернуть'],answer:0,explain:'Please say that again — попроси повторить.'},outcome:'Ты можешь попросить повторить непонятное.'},
{module:'МОДУЛЬ 9 · ЗАКРЕПЛЕНИЕ',title:'Итоговый диалог A1-старт',tag:'ЭКЗАМЕН',english:'Hello. I need help. What time is the train?',meaning:'Здравствуйте. Мне нужна помощь. Во сколько поезд?',pronounce:'хэлоу · ай нид хелп · уот тайм из зэ трэйн',why:'Финальная ситуация соединяет знакомство, просьбу и вопрос.',rule:'Ты уже используешь: кто → действие, вопросы с What time и просьбу I need.',tip:'Не стремись к идеальному акценту. Главное — понятный порядок и нужные слова.',build:['Hello','I','need','help','What','time','is','the','train'],practiceTitle:'Собери итоговый диалог',practiceHint:'Приветствие → просьба → вопрос о времени.',quiz:{q:'Что ты теперь умеешь?',options:['спросить, попросить и объяснить простую ситуацию','свободно говорить на любую тему','сдать международный экзамен C1'],answer:0,explain:'Это старт A1: реальные короткие ситуации, а не обещание свободного языка.'},outcome:'Ты прошёл 60 уроков и готов к итоговой проверке A1-старта.'}
);
